name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 4.240.112.52
          username: udayraj
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: bash /home/udayraj/deploy.sh
